name: Build frontend

on:
  workflow_call:
  workflow_dispatch:

jobs:
  job_build_frontend:
    name: Build frontend code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend # Falls Frontend sich im Unterordner "Frontend" befindet

    steps:
      - name: Checkout code
        uses: actions/checkout@v4